# Generated by Django 4.2.5 on 2024-06-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reg_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_pack', models.CharField(choices=[('family', 'family'), ('friends', 'friends'), ('couple', 'couple'), ('comapnya_pack', 'company_pack')], max_length=50)),
                ('price', models.IntegerField()),
                ('details', models.TextField()),
            ],
        ),
    ]
