# Generated by Django 4.2.5 on 2024-06-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_visit_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resort_Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='image/')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
