# Generated by Django 4.2.5 on 2024-06-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_resort_pack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit_packages',
            old_name='package_no',
            new_name='no_of_rooms',
        ),
    ]
