# Generated by Django 4.2.5 on 2024-06-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_package_no_visit_packages_no_of_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit_packages',
            name='img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
