# Generated by Django 4.2.5 on 2024-06-25 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_resort_packs_delete_resort_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chekin_date', models.DateField()),
                ('chekout_date', models.DateField()),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resort_packs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reg_guest')),
            ],
        ),
    ]
