# Generated by Django 4.2.5 on 2024-06-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='chekout_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='chekin_date',
            field=models.IntegerField(),
        ),
    ]
