# Generated by Django 4.2.5 on 2024-06-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_booking_chekout_date_booking_booking_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_no',
        ),
    ]
