# Generated by Django 4.2.5 on 2024-06-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_booking_booking_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='chekin_date',
        ),
    ]
