# Generated by Django 4.2.4 on 2024-07-13 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_booking_chekin_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booking')),
            ],
        ),
        migrations.DeleteModel(
            name='Visit_Package',
        ),
        migrations.DeleteModel(
            name='Visit_Packages',
        ),
    ]
